/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface accountsEntity {
  'account_type': string;
  'code': string | null;
  'commodity_guid': string | null;
  'commodity_scu': number;
  'description': string | null;
  'guid': string;
  'hidden': number | null;
  'name': string;
  'non_std_scu': number;
  'parent_guid': string | null;
  'placeholder': number | null;
}
export interface billtermsEntity {
  'cutoff': number | null;
  'description': string;
  'discount_denom': string | null;
  'discount_num': string | null;
  'discountdays': number | null;
  'duedays': number | null;
  'guid': string;
  'invisible': number;
  'name': string;
  'parent': string | null;
  'refcount': number;
  'type': string;
}
export interface booksEntity {
  'guid': string;
  'root_account_guid': string;
  'root_template_guid': string;
}
export interface budget_amountsEntity {
  'account_guid': string;
  'amount_denom': string;
  'amount_num': string;
  'budget_guid': string;
  'id'?: number;
  'period_num': number;
}
export interface budgetsEntity {
  'description': string | null;
  'guid': string;
  'name': string;
  'num_periods': number;
}
export interface commoditiesEntity {
  'cusip': string | null;
  'fraction': number;
  'fullname': string | null;
  'guid': string;
  'mnemonic': string;
  'namespace': string;
  'quote_flag': number;
  'quote_source': string | null;
  'quote_tz': string | null;
}
export interface customersEntity {
  'active': number;
  'addr_addr1': string | null;
  'addr_addr2': string | null;
  'addr_addr3': string | null;
  'addr_addr4': string | null;
  'addr_email': string | null;
  'addr_fax': string | null;
  'addr_name': string | null;
  'addr_phone': string | null;
  'credit_denom': string;
  'credit_num': string;
  'currency': string;
  'discount_denom': string;
  'discount_num': string;
  'guid': string;
  'id': string;
  'name': string;
  'notes': string;
  'shipaddr_addr1': string | null;
  'shipaddr_addr2': string | null;
  'shipaddr_addr3': string | null;
  'shipaddr_addr4': string | null;
  'shipaddr_email': string | null;
  'shipaddr_fax': string | null;
  'shipaddr_name': string | null;
  'shipaddr_phone': string | null;
  'tax_included': number | null;
  'tax_override': number;
  'taxtable': string | null;
  'terms': string | null;
}
export interface employeesEntity {
  'acl': string;
  'active': number;
  'addr_addr1': string | null;
  'addr_addr2': string | null;
  'addr_addr3': string | null;
  'addr_addr4': string | null;
  'addr_email': string | null;
  'addr_fax': string | null;
  'addr_name': string | null;
  'addr_phone': string | null;
  'ccard_guid': string | null;
  'currency': string;
  'guid': string;
  'id': string;
  'language': string;
  'rate_denom': string;
  'rate_num': string;
  'username': string;
  'workday_denom': string;
  'workday_num': string;
}
export interface entriesEntity {
  'action': string | null;
  'b_acct': string | null;
  'b_paytype': number | null;
  'b_price_denom': string | null;
  'b_price_num': string | null;
  'b_taxable': number | null;
  'b_taxincluded': number | null;
  'b_taxtable': string | null;
  'bill': string | null;
  'billable': number | null;
  'billto_guid': string | null;
  'billto_type': number | null;
  'date'?: Date;
  'date_entered'?: Date | null;
  'description': string | null;
  'guid': string;
  'i_acct': string | null;
  'i_disc_how': string | null;
  'i_disc_type': string | null;
  'i_discount_denom': string | null;
  'i_discount_num': string | null;
  'i_price_denom': string | null;
  'i_price_num': string | null;
  'i_taxable': number | null;
  'i_taxincluded': number | null;
  'i_taxtable': string | null;
  'invoice': string | null;
  'notes': string | null;
  'order_guid': string | null;
  'quantity_denom': string | null;
  'quantity_num': string | null;
}
export interface gnclockEntity {
  'Hostname': string | null;
  'PID': number | null;
}
export interface invoicesEntity {
  'active': number;
  'billing_id': string | null;
  'billto_guid': string | null;
  'billto_type': number | null;
  'charge_amt_denom': string | null;
  'charge_amt_num': string | null;
  'currency': string;
  'date_opened'?: Date | null;
  'date_posted'?: Date | null;
  'guid': string;
  'id': string;
  'notes': string;
  'owner_guid': string | null;
  'owner_type': number | null;
  'post_acc': string | null;
  'post_lot': string | null;
  'post_txn': string | null;
  'terms': string | null;
}
export interface jobsEntity {
  'active': number;
  'guid': string;
  'id': string;
  'name': string;
  'owner_guid': string | null;
  'owner_type': number | null;
  'reference': string;
}
export interface lotsEntity {
  'account_guid': string | null;
  'guid': string;
  'is_closed': number;
}
export interface ordersEntity {
  'active': number;
  'date_closed'?: Date;
  'date_opened'?: Date;
  'guid': string;
  'id': string;
  'notes': string;
  'owner_guid': string;
  'owner_type': number;
  'reference': string;
}
export interface pricesEntity {
  'commodity_guid': string;
  'currency_guid': string;
  'date'?: Date;
  'guid': string;
  'source': string | null;
  'type': string | null;
  'value_denom': string;
  'value_num': string;
}
export interface recurrencesEntity {
  'id'?: number;
  'obj_guid': string;
  'recurrence_mult': number;
  'recurrence_period_start': Date;
  'recurrence_period_type': string;
  'recurrence_weekend_adjust': string;
}
export interface schedxactionsEntity {
  'adv_creation': number;
  'adv_notify': number;
  'auto_create': number;
  'auto_notify': number;
  'enabled': number;
  'end_date': Date | null;
  'guid': string;
  'instance_count': number;
  'last_occur': Date | null;
  'name': string | null;
  'num_occur': number;
  'rem_occur': number;
  'start_date': Date | null;
  'template_act_guid': string;
}
export interface slotsEntity {
  'double_val': number | null;
  'gdate_val': Date | null;
  'guid_val': string | null;
  'id'?: number;
  'int64_val': string | null;
  'name': string;
  'numeric_val_denom': string | null;
  'numeric_val_num': string | null;
  'obj_guid': string;
  'slot_type': number;
  'string_val': string | null;
  'timespec_val'?: Date | null;
}
export interface splitsEntity {
  'account_guid': string;
  'action': string;
  'guid': string;
  'lot_guid': string | null;
  'memo': string;
  'quantity_denom': string;
  'quantity_num': string;
  'reconcile_date'?: Date | null;
  'reconcile_state': string;
  'tx_guid': string;
  'value_denom': string;
  'value_num': string;
}
export interface taxtable_entriesEntity {
  'account': string;
  'amount_denom': string;
  'amount_num': string;
  'id'?: number;
  'taxtable': string;
  'type': number;
}
export interface taxtablesEntity {
  'guid': string;
  'invisible': number;
  'name': string;
  'parent': string | null;
  'refcount': string;
}
export interface transactionsEntity {
  'currency_guid': string;
  'description': string | null;
  'enter_date'?: Date | null;
  'guid': string;
  'num': string;
  'post_date'?: Date | null;
}
export interface vendorsEntity {
  'active': number;
  'addr_addr1': string | null;
  'addr_addr2': string | null;
  'addr_addr3': string | null;
  'addr_addr4': string | null;
  'addr_email': string | null;
  'addr_fax': string | null;
  'addr_name': string | null;
  'addr_phone': string | null;
  'currency': string;
  'guid': string;
  'id': string;
  'name': string;
  'notes': string;
  'tax_inc': string | null;
  'tax_override': number;
  'tax_table': string | null;
  'terms': string | null;
}
export interface versionsEntity {
  'table_name': string;
  'table_version': number;
}
